version: "3.8"

services:
  
  discount-api.database:
    container_name: discount-api.database
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - discount-api.database
    volumes:
      - discount-api.database:/var/lib/postgresql/data:rw
      
volumes:
  discount-api.database: