version: "3.8"

services:
  
  basket-api.database:
    container_name: basket-api.database
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - basket-api-network
        
  basket-api.app:
    container_name: basket-api.app
    build: .
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings__Redis=basket-api.database:6379"
    ports:
      - "8002:8080"
    depends_on:
      - basket-api.database
    networks:
      - basket-api-network
      - discount-grpc-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
  
networks:
  basket-api-network:
    driver: bridge
  discount-grpc-network:
    driver: bridge
