version: "3.8"

services:
  productApi.database:
    container_name: productApi.database
    image: postgres:latest
    environment:
      POSTGRES_DB: productApi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - productApi.database:/var/lib/postgresql/data:rw

#  productApi.app:
#    container_name: productApi.app

volumes:
  productApi.database: