version: "3.8"

services:
  
  productApi-DB:
    container_name: productApi-DB
    image: postgres:latest
    environment:
      POSTGRES_DB: productApi-DB
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - productApi-DB:/var/lib/postgresql/data:rw

#  productApi-App:
#    container_name: productApi-App

volumes:
  productApi-DB: